<a href="https://colab.research.google.com/github/ericson-j-santos/PYTHON_IMPRESSIONADOR/blob/main/numpy_10_exercicios_parte_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercício

Você é um gerente de vendas e tem os dados de vendas de três produtos diferentes (Produto A, Produto B, Produto C) para os últimos 5 dias em um array 2D NumPy. Cada linha do array representa um produto e cada coluna representa um dia. Seu trabalho é calcular as vendas totais para cada produto e para cada dia.

Use o seguinte array para sua análise:

* Cada linha abaixo do vetor vendas, representa um produto, produto A, produto B e produto C;
* E cada coluna é um dia, sendo total de 5 dias;
* Ultimos 5 dias = ontem, anteontem, ...
```python
vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])
```

**Solução:**


In [5]:
import numpy as np

vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])

vendas_produto = np.sum(vendas, axis=1)
print(vendas_produto)
# [325 433 368]


[325 433 368]


In [5]:
print(f"Vendas totais para o produto A: {vendas_produto[0]}")
print(f"Vendas totais para o produto B: {vendas_produto[1]}")
print(f"Vendas totais para o produto C: {vendas_produto[2]}")
# Vendas totais para o produto A: 325
# Vendas totais para o produto B: 433
# Vendas totais para o produto C: 368

Vendas totais para o produto A: 325
Vendas totais para o produto B: 433
Vendas totais para o produto C: 368


In [6]:
vendas_dia = np.sum(vendas, axis=0)
print(vendas_dia)
# [207 225 216 234 244]


[207 225 216 234 244]


In [7]:
print(f"Vendas totais para o dia 1: {vendas_dia[0]}")
print(f"Vendas totais para o dia 2: {vendas_dia[1]}")
print(f"Vendas totais para o dia 3: {vendas_dia[2]}")
print(f"Vendas totais para o dia 4: {vendas_dia[3]}")
print(f"Vendas totais para o dia 5: {vendas_dia[4]}")
# Vendas totais para o dia 1: 207
# Vendas totais para o dia 2: 225
# Vendas totais para o dia 3: 216
# Vendas totais para o dia 4: 234
# Vendas totais para o dia 5: 244

Vendas totais para o dia 1: 207
Vendas totais para o dia 2: 225
Vendas totais para o dia 3: 216
Vendas totais para o dia 4: 234
Vendas totais para o dia 5: 244


In [2]:
print(range(5))
# range(0, 5)

range(0, 5)


In [1]:
print(list(range(5)))
# [0, 1, 2, 3, 4]

[0, 1, 2, 3, 4]


In [8]:
for i in range(5):
    print(f"Vendas totais para o dia {i+1}: {vendas_dia[i]}.")
# Vendas totais para o dia 1: 207.
# Vendas totais para o dia 2: 225.
# Vendas totais para o dia 3: 216.
# Vendas totais para o dia 4: 234.
# Vendas totais para o dia 5: 244.


Vendas totais para o dia 1: 207.
Vendas totais para o dia 2: 225.
Vendas totais para o dia 3: 216.
Vendas totais para o dia 4: 234.
Vendas totais para o dia 5: 244.
